### ISSUE TITLE
Trying to load libglfw3.dylib on Ubuntu

### ISSUE THREAD

**Issue by jpnk** [jellymann/mittsu#1]
here's what i got:

    /home/jay/usr/lib/ruby/2.3.0/fiddle/import.rb:86:in `rescue in block in dlload': can't load /home/jay/usr/lib/libglfw3.dylib (Fiddle::DLError)
    	from /home/jay/usr/lib/ruby/2.3.0/fiddle/import.rb:83:in `block in dlload'
    	from /home/jay/usr/lib/ruby/2.3.0/fiddle/import.rb:74:in `collect'
    	from /home/jay/usr/lib/ruby/2.3.0/fiddle/import.rb:74:in `dlload'
    	from /home/jay/usr/lib/ruby/gems/2.3.0/gems/opengl-bindings-1.5.3/lib/glfw.rb:421:in `load_lib'
    	from /home/jay/usr/lib/ruby/gems/2.3.0/gems/mittsu-0.1.0/lib/mittsu/renderers/glfw_window.rb:5:in `<top (required)>'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from /home/jay/usr/lib/ruby/gems/2.3.0/gems/mittsu-0.1.0/lib/mittsu/renderers/opengl_renderer.rb:9:in `<top (required)>'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from /home/jay/usr/lib/ruby/gems/2.3.0/gems/mittsu-0.1.0/lib/mittsu/renderers.rb:1:in `<top (required)>'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from /home/jay/usr/lib/ruby/gems/2.3.0/gems/mittsu-0.1.0/lib/mittsu.rb:12:in `<top (required)>'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    	from /home/jay/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    	from ./game.rb:6:in `<main>'

`game.rb` is a slightly modified version of the example program from the readme. the glfw installation is fine, i can use it from both C and Ruby (through another gem). mittsu should've loaded `libglfw.so` from the same directory. the right way to load the lib seems to be this: https://github.com/vaiorabbit/ruby-opengl/blob/master/sample/util/setup_dll.rb#L37
so the problem is in `lib/mittsu/renderers/glfw_window.rb`.
when i replaced `GLFW.load_lib('libglfw3.dylib', path)` with `GLFW.load_lib()` i got a core dump. so i'd like to hear your opinion before i continue poking on my own, i'm kinda of a noob when it comes to ruby.

P.S. i couldn't run the game without manually installing pry.

**Comment by jellymann** [comment]
Hi @jpnk 

You're right, the GLFW load_lib call is still very OSX-specific at the moment, I'm going to put in a condition on the platform.

I seem to have gotten a core dump on my side as well, but I don't know if it's for the same reason. Looks like my graphics driver might be missing on my linux box. Do you mind attaching the dump so I can take a look?

**Comment by jpnk** [comment]
the program i ran this time is an exact copy of the readme example.
[core.zip](https://github.com/jellymann/mittsu/files/135596/core.zip)
[stderr.txt](https://github.com/jellymann/mittsu/files/135603/stderr.txt)
it also produced `OpenGLRenderer 71` seemingly to stdout but i couldn't redirect that to a file.
`pkg-config --modversion glfw3` gives `3.1.2` but here https://github.com/vaiorabbit/ruby-opengl/blob/master/lib/glfw.rb `3.1.0` is expected (not sure if that's relevant though).

**Comment by jpnk** [comment]
> Looks like my graphics driver might be missing

do other glfw gems work? on my system `glfw3` works fine (together with `opengl`).

**Comment by jellymann** [comment]
It looks like we're getting the same segfault originating at glfw.rb:493.

`OpenGLRenderer 71` is printed by Mittsu on startup. I built the OpenGLRenderer after THREE.js's WebGLRenderer which happened to be at revision 71 at the time.

My glfw3 version is 3.1.1, but it's the same version on my mac, so I don't think the patch version makes a difference.

I'll investigate the `glfw3` and `opengl` gems if they provide better cross-platform support.

**Comment by jellymann** [comment]
@jpnk I think I've narrowed down the issue.

The segfault is happening because `glfwCreateWindow` is failing and returning a null pointer. This causes the segfault when the callbacks are registered.

The window creation could fail for a number of reasons, but the most common one is that the required OpenGL version is not available. Mittsu requires OpenGL 3.3+ at the moment, while a lot of Linux drivers only provide version 2.1.

Can you tell me what hardware you are running on and the output of `glxinfo`?

**Comment by jpnk** [comment]
[glxinfo.txt](https://github.com/jellymann/mittsu/files/141665/glxinfo.txt)
your guess is probably correct. no rotating boxes for me:)

**Comment by jellymann** [comment]
`OpenGL version string: 2.1 Mesa 10.1.3`
Looks like that's the case. Sorry about that, thanks for helping me pick these things up :)  

I've made the requirements more clear on the README and the gem page.

I'll probably need to do some kind of OpenGL version detection before-hand, and also add legacy OpenGL support at some stage, since it seems these low-end intel chips are quite common.
