### ISSUE TITLE
Using MeshPhongMaterial not showing any object on screen

### ISSUE THREAD

**Issue by taufikobet** [jellymann/mittsu#24]
First, I would like to thank for Mittsu. Awesome work!

I tried to poke around the code and change the `MeshBasicMaterial` to `MeshPhongMaterial` but on runtime there's no visible object presented.

I might missing something, I guess.

**Comment by jellymann** [comment]
Hi @taufikobet, thanks for giving Mittsu a try!

Did you add a light source to the scene?

Unlike `Basic` materials, `Phong` and `Lambert` materials react to light sources, which means if there are no light sources then they will render completely unlit, i.e. black.

**Comment by taufikobet** [comment]
Thank you! 

Using

```
light = Mittsu::AmbientLight.new(0xffffff)
scene.add(light)
```

works.
