### ISSUE TITLE
Currently doesn't work out of the box on High Sierra

### ISSUE THREAD

**Issue by halfbyte** [jellymann/mittsu#61]
Hiya,

I just tried to start playing with this great little library, unfortunately the steps lined out in the README do not lead to executable code on my Mac.

The reason seems to be that at some point, "libglfw3.dylib" has been renamed to "libglfw.3.dylib" in GLFW, maybe with the 3.2 release? Your README states that mittsu only works with 3.1 but it's not really easy to install a 3.1 via homebrew.

Is there a specific reason you need to load "libglfw3.dylib" instead of just loading ""libglfw.dylib" as opengl-bindings would do by default? In my homebrew installation they point to the same thing?

Willing to do a PR for changing this, but as my experience with this stuff is limited, I have no good grasp on the possible consequences.

**Comment by jellymann** [comment]
@halfbyte Thanks for picking this issue up. I'll have a look to see if I can make the library detection work better, as well as look into GLFW 3.2 support as well, once I have some time.

I don't have anything running High Sierra, so I won't be able to test that right now.

**Comment by jellymann** [comment]
@halfbyte I just had a similar issue happen to a friend of mine and we solved it by settings the environment variable: `export MITTSU_LIBGLFW_FILE=libglfw.3.dylib`
