### ISSUE TITLE
2D support?

### ISSUE THREAD

**Issue by Alihusejn** [jellymann/mittsu#67]

**Comment by jellymann** [comment]
@Alihusejn Mittsu is primarily for 3D graphics. There is a "Sprite" class that can render 2D images in a way similar to most 2D graphics libraries, but Mittsu does not provide a lot of support for that sort of thing, and it likely never will.

If you would like to do 2D graphics in Ruby, I would recommend taking a look at [Gosu](https://github.com/gosu/gosu).
