### ISSUE TITLE
get_platform undefined when running examples

### ISSUE THREAD

**Issue by jonzerstyle** [jellymann/mittsu#76]
On Ubuntu and CentOS when trying to run example scripts I get error:
mittsu/lib/mittsu/renderers/generic_lib.rb:4:in `discover': undefined method `get_platform' for OpenGL:Module (NoMethodError)

After fooling around I found if I force include the opengl-bindings from home rbenv path it works without issue: (excuse my ignorance if there is a better way)
Example:
ruby -I/$HOME/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/opengl-bindings-1.6.7/lib 05_earth_example.rb

Huge fan of this repo, thank you very much for the work here.  I found it perfect for interfacing to Ball Aerospace COSMOS telemetry feeds.

**Comment by jellymann** [comment]
Hi @jonzerstyle, I can't seem to reproduce the issue.

On a fresh install of Ubuntu I did the following:

1. installed rbenv
2. installed ruby 2.2.2
3. installed glfw3
4. cloned mittsu
5. `bundle install`
6. `ruby examples/05_earth_example.rb`

Could you please provide more information about your system? Version of ubuntu, version of bundler, what gems you have installed, etc?

**Comment by jonzerstyle** [comment]
Hi Daniel,

Sure no problem. The Ubuntu version is 16.04.5 LTS. Kernel
4.14.3-041403-generic.

**Comment by jonzerstyle** [comment]
*** LOCAL GEMS ***

ansi (1.5.0)
benchmark-ips (2.7.2)
bigdecimal (1.2.6)
builder (3.2.3)
bundler (1.16.2)
chunky_png (1.3.11)
codeclimate-test-reporter (1.0.9)
coderay (1.1.2)
cosmos (3.9.1)
coveralls (0.8.19)
digest-crc (0.4.1)
docile (1.1.5)
equatable (0.5.0)
ffi (1.10.0, 1.9.25)
httpclient (2.8.3)
io-console (0.4.3)
json (2.1.0, 1.8.6, 1.8.1)
method_source (0.9.2, 0.9.0, 0.8.2)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.4.3)
minitest-reporters (1.3.6)
mittsu (0.3.0)
nokogiri (1.8.5, 1.8.3)
opengl (0.9.2)
opengl-bindings (1.6.7, 1.6.6)
pastel (0.7.2)
power_assert (0.2.2)
pry (0.12.2, 0.11.3, 0.10.4)
pry-doc (0.13.4, 0.6.0)
psych (2.0.8)
puma (3.11.4)
qtbindings (4.8.6.5)
rack (2.0.5)
rake (12.3.1, 10.5.0, 10.4.2)
rdoc (6.0.4, 4.3.0, 4.2.0)
ruby-progressbar (1.10.0)
ruby-termios (0.9.6)
rubyserial (0.2.4)
rubyzip (1.2.1, 1.1.7)
simplecov (0.12.0)
simplecov-html (0.10.2)
slop (3.6.0)
snmp (1.3.1, 1.2.0)
term-ansicolor (1.7.1)
test-unit (3.0.8)
thor (0.19.4)
tins (1.20.2)
tty-color (0.4.3, 0.4.2)
tty-command (0.6.0)
uuidtools (2.1.5)
yard (0.9.16, 0.9.14)

**Comment by jellymann** [comment]
Could be something to do with the fact that you have to different versions of opengl-bindings installed.

Try running the example prefixed with `bundle exec`? If that doesn't work, try uninstalling opengl-bindings 1.6.6

**Comment by jonzerstyle** [comment]
Yep you were right! Running 'bundle exec ruby examples/...' worked.  Thank
you.

On Jan 23, 2019 10:52 AM, "Daniel Smith" <notifications@github.com> wrote:

Could be something to do with the fact that you have to different versions
of opengl-bindings installed.

Try running the example prefixed with bundle exec? If that doesn't work,
try uninstalling opengl-bindings 1.6.6

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jellymann/mittsu/issues/76#issuecomment-456922286>, or mute
the thread

**Comment by jellymann** [comment]
Glad I could help. I'd also suggest adding `alias be="bundle exec "` to your .bashrc so you can just run `be ruby ...` instead of having to type out `bundle exec` every time.

**Comment by jonzerstyle** [comment]
Very good suggestion. Thanks again 😊
