### ISSUE TITLE
Issue drawing lines

### ISSUE THREAD

**Issue by alxx** [jellymann/mittsu#77]
I wanted to see a grid, but `GridHelper` isn't implemented, so I thought to draw my own lines and got into this issue:

> /Users/alxx/.rvm/gems/ruby-2.4.1/gems/mittsu-0.3.0/lib/mittsu/renderers/opengl/core/object_3d.rb:25:in 'init': undefined method 'initted' for #<Mittsu::LineBasicMaterial:0x007f9337593180> (NoMethodError)

Relevant code portion:

```ruby 
  line_material = Mittsu::LineBasicMaterial.new(color: 0x1122ff)
  geometry = Mittsu::Geometry.new
  geometry.vertices << Mittsu::Vector3.new(0,0,0)
  geometry.vertices << Mittsu::Vector3.new(20,0,0)
  line = Mittsu::Line.new(line_material, geometry)
  scene.add(line)
```

**Comment by jellymann** [comment]
@alxx it looks like you've put the parameters the wrong way around in your call to `Line.new`.

Try replacing it with the following:
```ruby
line = Mittsu::Line.new(geometry, line_material)
```

**Comment by alxx** [comment]
Thanks, @jellymann
